"""
This script reads a pdf file with the income generated by a KBC bank account.
This scipt only work if:
- The pdf file is in Dutch (message and account number will not be read correctly if not)
- The pdf file is from KBC bank
- The pdf file contains only the income and not the expenses

The script does not work with the dummy file 
because I edited the file to remove personal information.
This changed the order of how the information is read by python.
"""

import re
from datetime import datetime
from tools.pdf_reader import read_pdf
from model.payment_receipts import PaymentReceipt


account_receiver = ''

def get_global_account_receiver(pages):
    """ Get the account of the receiver """
    global account_receiver
    account_receiver_match = re.search(r'rekening\n([A-Z0-9 ]+)', pages[0])
    if account_receiver_match:
        account_receiver = account_receiver_match.group(1)[:-4] 

def split_data(pages):
    """ Split the data into a list of transactions """
    # split the data into a list of transactions
    pattern = re.compile(r'\d{2}-\d{2}-\d{4} .+? \d{1,6},\d{2} EUR')
    transactions = []
    for page in pages:
        matches = list(pattern.finditer(page))
        start = 0

        for i, match in enumerate(matches):
            end = match.end()
            if i < len(matches) - 1:
                next_start = matches[i + 1].start()
                transactions.append(page[start:next_start].strip())
                start = next_start
            else:
                transactions.append(page[start:].strip())
    return transactions

def convert_to_payment(transaction):
    """ Convert a transaction string to a Payment object """
    # Extract date, name and amount
    date_name_amount_match = re.search(r'(\d{2}-\d{2}-\d{4}) (.+?) (\d{1,6},\d{2}) EUR', transaction)
    
    date = date_name_amount_match.group(1) if date_name_amount_match else None
    date = datetime.strptime(date, '%d-%m-%Y') if date else None
    
    name = date_name_amount_match.group(2) if date_name_amount_match else None
    
    amount = date_name_amount_match.group(3) if date_name_amount_match else None
    amount = float(amount.replace(',', '.')) if amount else None
    
    # Extract account number
    account_number_match = re.search(r'Rekeningnummer\n([A-Z0-9 ]+)', transaction)
    account_number = account_number_match.group(1) if account_number_match else None
    
    # Extract message
    message_match = re.search(r'Mededeling\n(.+)', transaction, re.DOTALL)
    message = message_match.group(1) if message_match else None
    
    # Remove "overschrijving" or "Instantoverschrijving" and anything after it if they are at the end of the message
    if message:
        message = re.sub(r'(\nOverschrijving|\nTijdstip\n\d{2}\.\d{2} uur\nInstantoverschrijving).*$', '', message, flags=re.DOTALL).strip()
    
    # Create Receipt object
    payment = PaymentReceipt(name, amount, date, account_number, account_receiver, message)
    
    return payment
    

def save_to_database(pages):
    """ Save the transactions to the database """
    get_global_account_receiver(pages)
    list = split_data(pages)
    payment_receipt_list = [convert_to_payment(transaction) for transaction in list]
    PaymentReceipt.save_payments_to_database([transaction for transaction in payment_receipt_list if transaction.name != 'Opneming'])
            
if __name__ == "__main__":
    file_path = 'private/ontvangsten-11okt.pdf'
    pdf_pages = read_pdf(file_path)
    save_to_database(pdf_pages)